#!/bin/bash 
#timer timeout 0 every 1
log ${rundir}/log_nvt_${system}.dat append

units ${units}
atom_style atomic

if "${restart_from} == data" then "read_data ${data_file}"
if "${restart_from} == data" then "reset_timestep 0"
if "${restart_from} == continuation" then "read_restart ${rundir}/restart_nvt_${system}.*"

mass 1 12.011
pair_style ${pair_style}
pair_coeff ${pair_coeff}
#pair_coeff * * carbon.xml "Potential xml_label=GAP_2017_1_20_0_21_37_48_267" 6

neighbor 2.0 bin 
neigh_modify every 1 delay 0 check yes 

variable Nfreq equal 100
variable Nprint equal 100
variable Nevery equal 100
variable Nrepeat equal ${Nfreq}/${Nevery}
variable Ndump equal 100 
variable nAtoms equal atoms

group carbon type 1

timestep 0.001 

fix removeMomentum all momentum 1 linear 1 1 1 

compute T all temp 
fix TempAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} c_T 

variable P equal press 
fix PressAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} v_P 

variable v equal vol
fix vAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} v_v

compute PE all pe pair 
fix PEAve all ave/time ${Nevery} ${Nrepeat} ${Nfreq} c_PE
compute PEa all pe/atom pair

compute MSD all msd

thermo_style custom step cpu temp f_TempAve press f_PressAve f_PEAve vol f_vAve c_MSD[4] 
thermo_modify flush yes

thermo ${Nfreq}

#dump traj       all atom ${Ndump}  ${rundir}/NVT/dump_nvt_${system}.*.dat 
dump 1 all custom ${Ndump} ${rundir}/NVT/dump_custom.${system}.*.dat id type x y z fx fy fz c_PEa
dump_modify 1 pad 5

restart ${Ndump} ${rundir}/restart/restart_nvt_${system}.*
variable Nrun1 equal ${melt_timesteps}
variable Nrun2 equal (${Nrun1}+${cool_timesteps})

if "${melt_timesteps} > 0 && $(step) == 0" then "velocity all create ${t_melt} ${rand}"

run 0

fix integrate all nvt temp ${t_melt} ${t_melt} 0.1
if "$(step) < ${Nrun1}" then "run ${Nrun1} upto"
unfix integrate

fix integrate all nvt temp ${t_melt} ${t_cool} 0.1
if "$(step) < ${Nrun2}" then "run ${Nrun2} upto start ${Nrun1} stop ${Nrun2}"
unfix integrate

write_data ${rundir}/out_data_quench_${system}
